/**
 * StayFinder Real Estate Marketplace Constants
 * Aligned with Emmanuel Eseyin's PRD:
 * - Dual-mode: Buy & Rent houses
 * - Verified properties (Physical inspection & Title verification)
 * - Scheduled viewing slots
 * - Transparent fee structures (No viewing fee scams)
 */

export const PROPERTY_TYPES = [
  { id: 'all', label: 'All Properties' },
  { id: 'apartment', label: 'Apartments & Flats' },
  { id: 'detached_house', label: 'Detached Houses' },
  { id: 'duplex', label: 'Duplexes' },
  { id: 'penthouse', label: 'Penthouses' },
  { id: 'townhouse', label: 'Terraced Townhouses' },
  { id: 'luxury_villa', label: 'Villas & Mansions' },
];

export const MOCK_PROPERTIES = [
  {
    id: 'sf-201',
    title: 'Contemporary 3-Bedroom Serviced Waterfront Apartment',
    listingType: 'rent', // 'rent' | 'buy'
    propertyType: 'apartment',
    location: 'Lekki Phase 1, Lagos',
    neighborhood: 'Admiralty Way Waterfront',
    country: 'Nigeria',
    price: 3200,
    tenure: 'month', // 'month' | 'year'
    annualEquivalent: 38400,
    bedrooms: 3,
    bathrooms: 3,
    areaSqM: 185,
    isVerified: true,
    verificationTier: 'physical_inspected',
    verificationBadge: 'Verified Inspection & Title',
    noViewingFees: true,
    featured: true,
    lister: {
      name: 'Adeola Property Partners',
      type: 'Certified Agent',
      verifiedKYC: true,
      licenseNumber: 'LAG-REA-2024-88',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=120&h=120&q=80',
      phone: '+234 801 234 5678',
    },
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1000&q=80',
    ],
    description: 'Immaculately finished 3-bed apartment in a fully serviced waterfront access building. 24/7 uninterrupted power, treated water, fitted Italian kitchen, elevator access, and dedicated resident parking.',
    feeBreakdown: {
      rent: '$3,200/mo',
      serviceCharge: '$350/mo (Includes 24/7 power & security)',
      cautionDeposit: '$1,500 (Refundable)',
      legalAgency: '5% transparent agency fee',
      viewingFee: '$0 (StayFinder Scam-Free Guarantee)',
    },
    availableViewingSlots: [
      { date: 'Tomorrow', times: ['10:00 AM', '02:00 PM', '04:30 PM'] },
      { date: 'Saturday', times: ['11:00 AM', '01:30 PM', '03:30 PM'] },
      { date: 'Monday', times: ['09:30 AM', '12:00 PM'] },
    ],
    amenities: ['24/7 Power', 'Elevator', 'Swimming Pool', 'Fitted Kitchen', 'Gym', '24/7 Security', 'High-speed Fiber'],
  },
  {
    id: 'sf-202',
    title: 'Modern 5-Bedroom Fully Detached Smart Duplex with Pool',
    listingType: 'buy',
    propertyType: 'detached_house',
    location: 'Ikoyi, Lagos',
    neighborhood: 'Old Ikoyi Enclave',
    country: 'Nigeria',
    price: 850000,
    bedrooms: 5,
    bathrooms: 6,
    areaSqM: 520,
    isVerified: true,
    verificationTier: 'title_verified',
    verificationBadge: 'Governor’s Consent & Title Verified',
    noViewingFees: true,
    featured: true,
    lister: {
      name: 'Dr. Tunde Oladipo',
      type: 'Direct Landlord / Owner',
      verifiedKYC: true,
      licenseNumber: 'DIRECT-OWNER-771',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=120&h=120&q=80',
      phone: '+234 809 876 5432',
    },
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=80',
    ],
    description: 'Ultra-modern private detached residence featuring full home automation (control lighting, AC, and sound from mobile), private swimming pool, 2 maid rooms, cinema room, and stamped concrete compound.',
    feeBreakdown: {
      price: '$850,000 (Asking)',
      titleDocument: 'Governor’s Consent (Original Available for Legal Search)',
      viewingFee: '$0 (Free Verified In-Person Walkthrough)',
    },
    availableViewingSlots: [
      { date: 'Thursday', times: ['11:00 AM', '03:00 PM'] },
      { date: 'Saturday', times: ['10:00 AM', '12:30 PM', '04:00 PM'] },
    ],
    amenities: ['Private Pool', 'Smart Home Automation', 'Cinema Room', 'Borehole & Filtration', '2 Maid Rooms', 'CCTV & Electric Fence'],
  },
  {
    id: 'sf-203',
    title: 'Brand New 4-Bedroom Semi-Detached House with BQ',
    listingType: 'rent',
    propertyType: 'duplex',
    location: 'Chevron, Lekki',
    neighborhood: 'Chevron Tollgate Vicinity',
    country: 'Nigeria',
    price: 1800,
    tenure: 'month',
    annualEquivalent: 21600,
    bedrooms: 4,
    bathrooms: 4,
    areaSqM: 290,
    isVerified: true,
    verificationTier: 'physical_inspected',
    verificationBadge: 'Physically Inspected by StayFinder',
    noViewingFees: true,
    featured: false,
    lister: {
      name: 'Prime Heritage Realty',
      type: 'Certified Agent',
      verifiedKYC: true,
      licenseNumber: 'LAG-REA-2023-41',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=120&h=120&q=80',
      phone: '+234 812 345 6789',
    },
    images: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1000&q=80',
    ],
    description: 'Tastefully built 4-bedroom semi-detached duplex in a gated, secure estate with 24/7 security patrol. All rooms en-suite, spacious family lounge, pantry, and clean water treatment.',
    feeBreakdown: {
      rent: '$1,800/mo ($21,600/yr)',
      serviceCharge: '$180/mo',
      cautionDeposit: '$1,000',
      viewingFee: '$0 (Zero Fake Listing Scam Guarantee)',
    },
    availableViewingSlots: [
      { date: 'Tomorrow', times: ['11:00 AM', '01:00 PM', '04:00 PM'] },
      { date: 'Sunday', times: ['02:00 PM', '04:00 PM'] },
    ],
    amenities: ['All Rooms En-suite', 'Gated Estate', 'Clean Treated Water', 'Boys Quarters (BQ)', 'Fitted Wardrobes'],
  },
  {
    id: 'sf-204',
    title: 'Luxury 2-Bedroom High-Rise Penthouse with Panoramic Views',
    listingType: 'rent',
    propertyType: 'penthouse',
    location: 'Victoria Island, Lagos',
    neighborhood: 'Ahmadu Bello Way',
    country: 'Nigeria',
    price: 2600,
    tenure: 'month',
    annualEquivalent: 31200,
    bedrooms: 2,
    bathrooms: 2,
    areaSqM: 140,
    isVerified: true,
    verificationTier: 'physical_inspected',
    verificationBadge: 'Verified & Ready for Move-In',
    noViewingFees: true,
    featured: true,
    lister: {
      name: 'Victoria Bay Properties',
      type: 'Direct Landlord',
      verifiedKYC: true,
      licenseNumber: 'DIRECT-OWNER-409',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=120&h=120&q=80',
      phone: '+234 818 990 0112',
    },
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1000&q=80',
    ],
    description: 'Exclusive executive penthouse overlooking the Atlantic ocean and city skyline. Floor-to-ceiling soundproof acoustic glass, private terrace, 24/7 concierge desk, and rooftop lounge access.',
    feeBreakdown: {
      rent: '$2,600/mo',
      serviceCharge: '$280/mo (Full facilities included)',
      cautionDeposit: '$1,200',
      viewingFee: '$0 (StayFinder Verified)',
    },
    availableViewingSlots: [
      { date: 'Today', times: ['03:00 PM', '05:00 PM'] },
      { date: 'Friday', times: ['10:00 AM', '02:00 PM'] },
    ],
    amenities: ['Ocean Views', 'Rooftop Pool', 'Concierge & Valet', 'Soundproof Windows', 'Backup Generator'],
  },
  {
    id: 'sf-205',
    title: 'Exquisite 4-Bedroom Terraced Townhouse in Gated Community',
    listingType: 'buy',
    propertyType: 'townhouse',
    location: 'Banana Island, Lagos',
    neighborhood: 'Zone B Waterfront',
    country: 'Nigeria',
    price: 620000,
    bedrooms: 4,
    bathrooms: 5,
    areaSqM: 380,
    isVerified: true,
    verificationTier: 'title_verified',
    verificationBadge: 'Title Deed & Survey Verified',
    noViewingFees: true,
    featured: true,
    lister: {
      name: 'Highland Estates & Trust',
      type: 'Certified Developer',
      verifiedKYC: true,
      licenseNumber: 'LAG-DEV-2022-19',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=120&h=120&q=80',
      phone: '+234 803 111 2233',
    },
    images: [
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?auto=format&fit=crop&w=1000&q=80',
    ],
    description: 'Rare opportunity to acquire a turnkey luxury townhouse on Banana Island. Fully fitted Poggenpohl kitchen, private rooftop deck, dedicated generator, and 24/7 armed private estate security.',
    feeBreakdown: {
      price: '$620,000 (Clear Federal C of O)',
      viewingFee: '$0 (Verified Property Tour)',
    },
    availableViewingSlots: [
      { date: 'Saturday', times: ['10:30 AM', '01:00 PM', '03:30 PM'] },
      { date: 'Sunday', times: ['02:00 PM', '04:00 PM'] },
    ],
    amenities: ['Federal C of O', 'Clubhouse & Squash Court', 'Fiber Optic Ready', 'Rooftop Lounge', 'Armed Security'],
  },
  {
    id: 'sf-206',
    title: 'Cozy 1-Bedroom Studio Apartment for Young Professionals',
    listingType: 'rent',
    propertyType: 'apartment',
    location: 'Yaba, Lagos',
    neighborhood: 'Sabo Tech Hub Corridor',
    country: 'Nigeria',
    price: 650,
    tenure: 'month',
    annualEquivalent: 7800,
    bedrooms: 1,
    bathrooms: 1,
    areaSqM: 55,
    isVerified: true,
    verificationTier: 'physical_inspected',
    verificationBadge: 'Physically Inspected by StayFinder',
    noViewingFees: true,
    featured: false,
    lister: {
      name: 'Sabo Urban Living',
      type: 'Direct Landlord',
      verifiedKYC: true,
      licenseNumber: 'DIRECT-OWNER-118',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=120&h=120&q=80',
      phone: '+234 816 778 8990',
    },
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1000&q=80',
    ],
    description: 'Perfect starter home or remote work studio directly inside the Yaba innovation district. Modern kitchenette, prepaid meter, water heater, and tight neighborhood security.',
    feeBreakdown: {
      rent: '$650/mo',
      serviceCharge: '$80/mo (Security & cleaning)',
      cautionDeposit: '$300',
      viewingFee: '$0 (No Agent Inspection Fee)',
    },
    availableViewingSlots: [
      { date: 'Tomorrow', times: ['01:00 PM', '05:30 PM'] },
      { date: 'Saturday', times: ['12:00 PM', '03:00 PM'] },
    ],
    amenities: ['Prepaid Meter', 'Fitted Kitchenette', 'Water Treatment', 'Fiber Internet Available'],
  },
];
